import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '@/components/Layout';
import Hero from '@/components/home/Hero';
import Animation from '@/components/home/animation';

const Home: NextPage = function () {
  return (
    <Layout>
      <Head>
        <title>서동원 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </Layout>
  );
};

export default Home;
